Statisk path for js og css
UKMNorge/UKMrapporter pull request #113
Opened 2021-03-19 10:13 UTC by slogan-15

Bruker en final variable for å definere statisk path-en for å peke på resurser.

Deriverer fra: https://github.com/UKMNorge/UKMresources/issues/3

OBS: UKMconfig.inc.php er modifisert. Denne linjen er lagt til:
"# RESOURCES PLUGIN PATH
define('PLUGIN_PATH', 'https://' . UKM_HOSTNAME . '/wp-content/plugins/');"

2021-04-07 10:10 UTC, slogan-15 commented
For PR: https://github.com/UKMNorge/UKMplayback/pull/27

2021-04-08 14:23 UTC, mariusmandal requested changes

2021-04-08 14:23 UTC, mariusmandal commented on ukmrapporter.php
>          wp_enqueue_script('GOOGLEchart', 'https://www.google.com/jsapi');
Huh, men dette funker jo ikke? Den fila finnes ikke 😂

Fjern parameter to i funksjonen, for jquery-ui-style registreres av [UKMNorge/UKMresources](https://github.com/UKMNorge/UKMresources) så da trenger vi ikke å definere url her

2021-04-08 14:46 UTC, mariusmandal approved these changes

2021-04-08 14:46 UTC, merged