Rapport for arrangementer i fylke
UKMNorge/UKMrapporter pull request #120
Opened 2021-04-21 09:19 UTC by slogan-15

Close https://github.com/UKMNorge/UKMwp_dashboard/issues/35.

Tid: 7:30 timer

2021-04-22 10:22 UTC, mariusmandal requested changes
Jeg har gjort noen endringer direkte, og oppdaget noen svakheter:

- [x] Jeg har gjort menyen tilgjengelig for alle brukere (tidligere var den kun synlig for fylkeskontakter + UKM Norge)
- [x] Jeg har fjernet litt ubrukt kode

Vi må også gjøre noen endringer:
- [x] Rapporten må også vise sluttdato
- [x] Start kan hete "starter"
- [x] Slutt kan hete "ferdig" 

Det må være mulig å sortere listen som i dag
- [x] Alfabetisk etter kommune-navn
- [x] Etter start-dato (slik at man kan se hva som er neste arrangement)

Listen viser i dag alle arrangement som er registrert. Det må derfor legges til enda et valg når man henter ut rapporten:
- [ ] Vis kun kommende arrangement [ja/nei]
hvis nei:
- [ ] lag checkbox for kommende arrangement
- [ ] lag checkbox per sesong ( date(Y) til 2019)

2021-04-22 10:24 UTC, mariusmandal commented
OBS: her har jeg ikke klart å forutse alt i løsningsforslaget, og det blir derfor litt ekstra-arbeid. Jeg øker timeestimatet i coda som følge av dette.

I hovedsak: sorteringen endres, og vi må velge hvilken sesong/kommende arrangement vi ønsker å vise

2021-04-23 11:27 UTC, mariusmandal requested changes
- [x] Header for ferdig må stå over teksten (align right)
- [x] Vis kun kommende arrangement må være første boks man tar stilling til 
- [x] Sortering: dato-sorteringen må være uavhengig av kommune

**Nå er den sånn**
Kommune A
 - 1. jan arrangement 1
 - 5. feb Arrangement 2
 Kommune B
 - 12. jan Arrangement 3
 
 **men den må være sånn** (og dette alternativet må være valgt som standard)
 - 1. jan arrangement 1
 - 12. jan arrangement 3
 - 5. feb arrangement 2
 
Du kan la sorteringen vi har i dag være et alternativ nr 3 "sortert på dato, innad i kommunen"

2021-04-23 11:33 UTC, mariusmandal commented
Husk forresten å oppdatere tida brukt på denne @slogan-15 😊

2021-04-23 11:39 UTC, slogan-15 commented
"Sortering: dato-sorteringen må være uavhengig av kommune" tror jeg skal ta litt tid å implementers @mariusmandal

2021-04-23 11:40 UTC, mariusmandal commented
> "Sortering: dato-sorteringen må være uavhengig av kommune" tror jeg skal ta litt tid å implementers @mariusmandal

Ja, den er nok dessverre ikke så veldig enkel @slogan-15 :( Beklager at det ikke var med i opprinnelig løsningsforslag!

2021-04-23 11:42 UTC, slogan-15 commented
Helt i orden @mariusmandal 😊

2021-04-29 09:43 UTC, mariusmandal requested changes
Vi nærmer oss fort nå! 😃 

- [x] Send sms-knappen må bort (tror du kan sette `static $har_sms = false` eller lignende på rapport-klassen) 
- [x] "Sorter arrangement etter start dato" må være "Sorter arrangement etter startdato"
- [ ] Velg kolonner: her må "arrangement" alltid være valgt
- [ ] Listen "kommuner uten arrangement" kommer opp tom hos meg når jeg velger "sorter arrangement etter startdato" 
![Skjermbilde 2021-04-29 kl  11 40 48](https://user-images.githubusercontent.com/4747102/116531706-c0c15080-a8df-11eb-83ad-4cda4b310f09.png)

2021-04-30 10:46 UTC, slogan-15 commented
Jeg har ikke testet:

- [ ] Listen "kommuner uten arrangement" kommer opp tom hos meg når jeg velger "sorter arrangement etter startdato"

Grunnen er: alle kommuner hos meg har arrangementer.

2021-04-30 10:47 UTC, slogan-15 commented
Utviklingstid: + 2 timer.

2021-05-25 10:41 UTC, mariusmandal approved these changes

2021-05-25 10:41 UTC, merged